### ISSUE TITLE
Update for specification version 3.17

### ISSUE THREAD

**Issue by vinistock** [mtsmfm/language_server-protocol-ruby#36]
Hello!

I've tried using `generateFiles` to update the gem to the latest version of the specification, since it's missing some new features (like inlay hints, pull diagnostics, etc).

However, it looks like the specification was broken down into multiple markdown files using relative references. You can see this by searching for `include_relative` in the raw [specification markdown file](https://raw.githubusercontent.com/microsoft/language-server-protocol/gh-pages/_specifications/lsp/3.17/specification.md).

This makes the `generateFiles` script miss a lot of the interfaces since they are now defined in separate files.

Any suggestions/ideas on how to handle this?

The steps I took to run `generateFiles` were
- Updated the LSP version to 3.17 and the commit SHA to the most recent one
- Changed the fetch URL to `https://github.com/Microsoft/language-server-protocol/raw/${lspRepoRevision}/_specifications/lsp/${lspVersion}/specification.md`, which matches the current repo structure

**Comment by mtsmfm** [comment]
Close via https://github.com/mtsmfm/language_server-protocol-ruby/pull/37

I've just released 3.17.0.0. https://rubygems.org/gems/language_server-protocol/versions/3.17.0.0

**Comment by vinistock** [comment]
Thank you very much!
