### ISSUE TITLE
Use with Rails? (#to_json is overridden 😖)

### ISSUE THREAD

**Issue by rmosolgo** [mtsmfm/language_server-protocol-ruby#8]
Hi! 

Thanks for your work on this project! I'm trying to write a language server for GraphQL over at https://github.com/rmosolgo/graphql-ruby/pull/1144.

Everything works wonderfully when I run the project as described in README. But, I have a problem when I try to use it with Rails. 

The outgoing JSON is wrong because Rails overwrites the `to_json` method. In Rails, the JSON includes an invalid `"attributes"` key because of [their monkey-patch](https://github.com/rails/rails/blob/802678d3dc27f1659c7bbdc5c0bbb86af2b25349/activesupport/lib/active_support/core_ext/object/json.rb#L41). For example: 

```ruby 
Rails::VERSION::STRING
# 5.1.4 

# make a new result 
ir = LanguageServer::Protocol::Interface::InitializeResult.new(capabilities: {})

# try to make JSON 
# #to_json works: 
ir.to_json  # => "{\"capabilities\":{}}"
# #as_json _doesn't_ work, see the extra `attributes` key:
ir.as_json  # => {"attributes"=>{"capabilities"=>{}}}

# Inside a hash, even #to_json is broken:
{result: ir}.to_json  # => "{\"result\":{\"attributes\":{\"capabilities\":{}}}}" 

# However, JSON.dump still works: 
JSON.dump(result: ir)  # => "{\"result\":{\"capabilities\":{}}}"
```

You can see that the invalid behavior is introduced by Rails libraries: 

```ruby 
ir.method(:as_json).source_location
# => ["/Users/rmosolgo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/core_ext/object/json.rb", 50]
```

So, I think we could fix the Rails use case by using `JSON.dump` instead of `to_json` here: 

https://github.com/mtsmfm/language_server-protocol-ruby/blob/91214ec628d02daa52436ee4bd0057ff68edeb78/lib/language_server/protocol/transport/stdio/writer.rb#L9

What do you think of that change? Would it be appropriate to fix LSP + Rails? 

Thanks!

**Comment by mtsmfm** [comment]
close via https://github.com/mtsmfm/language_server-protocol-ruby/pull/10
